import { Metadata } from "next";

export const metadata: Metadata = {
  title: "ورود به سامانه",
  description: "Generated by amisa.me"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>{children}</div>;
}
