import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import MainLayout from "@/template/MainLayout";
import './globals.css'
import Favicon from './favicon.ico'
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


export const metadata: Metadata = {
  title: "گروه کیا قشم - Kiaqeshm Group",
  description:'Generated by amisa.me',
  icons: [{ rel: 'icon', url: Favicon.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <AppRouterCacheProvider>
          <MainLayout>{children}</MainLayout>
          <ToastContainer/>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
