import { Metadata } from "next";
import Order from "@/forms/Order";
import GlobalOrderProvider from "@/Provider/GlobalOrderProvider";

export const metadata: Metadata = {
  title: "ثبت سفارشات",
  description: "Generated by amisa.me",
};

export default async function page() {
  return (
    <div dir="rtl">
      <GlobalOrderProvider>
        <Order />
      </GlobalOrderProvider>
    </div>
  );
}
